### ISSUE TITLE
transpile failed with 'RuntimeError: Unsupported OS: macOS-10.16-x86_64-i386-64bit'

### ISSUE THREAD

**Issue by spartucus** [NethermindEth/warp#218]
### ENV
* MacOS Monterey 12.1
* Python 3.9
* solc Version: 0.8.11+commit.d7f03943.Darwin.appleclang

### log
```
% warp transpile ERC20.sol WARP
Traceback (most recent call last):
  File "/usr/local/bin/warp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/warp/cli/cli.py", line 199, in main
    warp()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/warp/cli/cli.py", line 53, in transpile
    output = transpile_from_solidity(file_path, contract_name)
  File "/usr/local/lib/python3.9/site-packages/warp/yul/main.py", line 53, in transpile_from_solidity
    with kudu_exe() as exe:
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/warp/kudu.py", line 39, in kudu_exe
    raise RuntimeError(f"Unsupported OS: {platform.platform()}")
RuntimeError: Unsupported OS: macOS-10.16-x86_64-i386-64bit
```

**Comment by murcake** [comment]
Hi, can you please tell me if the solution [described here](https://stackoverflow.com/a/65402241/7190191) works for you?

**Comment by spartucus** [comment]
Thanks @murcake !
`SYSTEM_VERSION_COMPAT=0` works!
