### ISSUE TITLE
nethersolc segfault -- dockerfile?

### ISSUE THREAD

**Issue by kevindarby** [NethermindEth/warp#385]
Hi, I think this is linux flavor issue, but, I started here: (in alpine) 

https://github.com/Shard-Labs/cairo-cli-docker

then

apk add git openssh nano build-base boost-dev gmp-dev cmake boost-static 
apk add libstdc++ curl ca-certificates python3-dev

#Then glib
#https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path
export GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc
export GLIBC_VERSION=2.30-r0
for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION}; do curl -sSL ${GLIBC_REPO}/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done 
apk add --allow-untrusted /tmp/*.apk 

pip install z3-solver
pip install sol-warp

nethersolc segfaults when I give it .sol file

and warp transpile gives me: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/warp/yul/utils.py", line 53, in get_solc_json
    capture_output=True,
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '[PosixPath('/usr/local/lib/python3.7/site-packages/warp/bin/linux/nethersolc'), '--optimize', '--combined-json', 'abi,ir-optimized-ast', 'Test.sol']' died with <Signals.SIGSEGV: 11>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/warp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/warp/cli/cli.py", line 246, in main
    warp()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/warp/cli/cli.py", line 53, in transpile
    output = transpile_from_solidity(file_path, contract_name)
  File "/usr/local/lib/python3.7/site-packages/warp/yul/main.py", line 45, in transpile_from_solidity
    abi, yul_json = get_requests(filepath, main_contract, ["abi", "ir-optimized-ast"])
  File "/usr/local/lib/python3.7/site-packages/warp/yul/utils.py", line 63, in get_requests
    output = get_solc_json(requests, filepath)
  File "/usr/local/lib/python3.7/site-packages/warp/yul/utils.py", line 57, in get_solc_json
    raise WarpException(err_msg) from e
warp.yul.WarpException.WarpException: nethersolc call failed: /usr/local/lib/python3.7/site-packages/warp/bin/linux/nethersolc: /usr/lib/libstdc++.so.6: no version information available (required by /usr/local/lib/python3.7/site-packages/warp/bin/linux/nethersolc)

**Comment by kevindarby** [comment]
by the way, I was able to resolve this by rebuilding nethersolc from scratch

**Comment by JorikSchellekens** [comment]
@swapnilraj can you think of a reason our builds would do this under alpine?
