### ISSUE TITLE
Transpiling Oracle.sol from uniswap v3 Core

### ISSUE THREAD

**Issue by FawadHa1der** [NethermindEth/warp#565]
This is the file and see error below https://github.com/Uniswap/v3-core/blob/main/contracts/libraries/Oracle.sol. I remove the ternary operators into simpler if blocks to get through the expected transpiration error. 

Unexpected error during transpilation
Error: Couldn't find StructDefinition Oracle.Observation
    at makeUserDefinedType (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:78:15)
    at peg$c195 (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:451:16)
    at peg$parseUserDefinedType (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:3849:26)
    at peg$parseSimpleType (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:3215:50)
    at peg$parseNonArrPtrType (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:4906:18)
    at peg$parseArrayPtrType (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:4923:14)
    at peg$parseType (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:5220:34)
    at peg$parseStart (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:644:18)
    at peg$parse (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:5229:18)
    at getNodeType (/Users/fawad/.config/yarn/global/node_modules/solc-typed-ast/dist/types/typeStrings/typeString_parser.js:56:30)
    at /Users/fawad/.config/yarn/global/node_modules/@nethermindeth/warp/build/utils/getTypeString.js:73:55
    at Array.map (<anonymous>)
    at getReturnTypeString (/Users/fawad/.config/yarn/global/node_modules/@nethermindeth/warp/build/utils/getTypeString.js:72:10)
    at createCallToFunction (/Users/fawad/.config/yarn/global/node_modules/@nethermindeth/warp/build/utils/functionGeneration.js:11:107)
    at createSplitFunction (/Users/fawad/.config/yarn/global/node_modules/@nethermindeth/warp/build/passes/ifFunctionaliser.js:117:64)
    at IfFunctionaliser.visitIfStatement (/Users/fawad/.config/yarn/global/node_modules/@nethermindeth/warp/build/passes/ifFunctionaliser.js:29:37)
Transpilation failed

**Comment by RohitRanjangit** [comment]
Hey @FawadHa1der 
I can compile the above contract without any error, you can see the transpiled contract from [here](http://sprunge.us/vkhbQ6). Can you provide exactly what solidity code you're transpiling?

**Comment by JorikSchellekens** [comment]
Hi @FawadHa1der warp wasn't officially packaged an released until this morning. If you update warp it should handle this.

**Comment by JorikSchellekens** [comment]
I'm going to close these but feel free to reopen if you're still having issues with it!
