### ISSUE TITLE
`bin/warp transpile solc_file -o .`  is not working anymore

### ISSUE THREAD

**Issue by rjnrohit** [NethermindEth/warp#822]
`bin/warp transpile solc_file -o .`  is not working anymore, it used to work before. Possibly because of the dir name clash with the solidity file name itself.

```
Error: ENOTDIR: not a directory, open 'order_of_eval.sol/A_sol_abi.json'
    at Object.openSync (node:fs:599:3)
    at Object.writeFileSync (node:fs:2221:35)
    at Object.outputFileSync (/Users/rohit/nmd/warp/node_modules/fs-extra/lib/output-file/index.js:31:15)
    at outputResult (/Users/rohit/nmd/warp/build/io.js:104:12)
    at /Users/rohit/nmd/warp/build/index.js:73:35
    at Array.map (<anonymous>)
    at Command.<anonymous> (/Users/rohit/nmd/warp/build/index.js:72:14)
    at Command.listener [as _actionHa

...
```

**Comment by rjnrohit** [comment]
#852
